import { mkdirSync, writeFileSync } from "node:fs";
import { artifactsDir, artifactPath, assertGitIgnoredArtifactPath } from "./paths";
import type { AvailabilityReport } from "./datasets";
import type { ExtractionSummary } from "./extract";
import type { EvalResult } from "./evaluate";
import type { LogRegParams } from "./model";
import type { InferenceReport } from "./inference";

/**
 * Artifact + report writers. Every write goes through `assertGitIgnoredArtifactPath`
 * so a generated artifact can NEVER land on a tracked path — feature tables, model
 * weights, and reports all live under the git-ignored `data/processed/signal-lab/`
 * (or outside the repo via HUM_DATA_DIR). Reports are honest by construction: no
 * fabricated numbers, every claim carries its caveats (ADR-0004 model-card rule).
 */

export function ensureArtifactsDir(env?: NodeJS.ProcessEnv): string {
  const dir = artifactsDir(env);
  assertGitIgnoredArtifactPath(dir, env);
  mkdirSync(dir, { recursive: true });
  return dir;
}

export function writeArtifactJson(name: string, value: unknown, env?: NodeJS.ProcessEnv): string {
  const path = artifactPath(name, env);
  assertGitIgnoredArtifactPath(path, env);
  writeFileSync(path, JSON.stringify(value, null, 2), "utf8");
  return path;
}

export function writeArtifactText(name: string, text: string, env?: NodeJS.ProcessEnv): string {
  const path = artifactPath(name, env);
  assertGitIgnoredArtifactPath(path, env);
  writeFileSync(path, text, "utf8");
  return path;
}

export function writeArtifactJsonl(name: string, rows: readonly unknown[], env?: NodeJS.ProcessEnv): string {
  const path = artifactPath(name, env);
  assertGitIgnoredArtifactPath(path, env);
  writeFileSync(path, rows.map((r) => JSON.stringify(r)).join("\n") + (rows.length ? "\n" : ""), "utf8");
  return path;
}

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

export function buildAvailabilityMarkdown(report: AvailabilityReport): string {
  const lines: string[] = [];
  lines.push("# Signal-Lab — Dataset Availability\n");
  lines.push(`Data root: \`${report.dataRoot}\` (git-ignored). Generated by \`@hum-ai/signal-lab\`.\n`);
  lines.push(
    `Usable for feature extraction today: **${report.summary.usableIds.join(", ") || "(none)"}** ` +
      `(${report.summary.usable}/${report.summary.total}).\n`,
  );
  lines.push("| dataset | status | audio domain | gap | penalty | usable | allowed (priors) | limitations |");
  lines.push("|---|---|---|---|---|---|---|---|");
  for (const d of report.datasets) {
    lines.push(
      `| \`${d.datasetId}\` | ${d.status} | ${d.audioDomain} | ${d.domainGap} | ${d.domainPenalty} | ` +
        `${d.usableForFeatureExtraction ? "yes" : "no"} | ${d.allowedModelUse.join(", ") || "—"} | ${d.limitations.join("; ") || "—"} |`,
    );
  }
  lines.push("\n> Governance (ADR-0005): public datasets are PRIORS only; only `native_hum` is hum truth. None present.\n");
  return lines.join("\n");
}

export function buildEvaluationMarkdown(ev: EvalResult): string {
  const l: string[] = [];
  l.push(`# Signal-Lab — Evaluation & Significance: ${ev.task}\n`);
  l.push(`Target space: \`${ev.targetSpace}\`. Labels: ${ev.labels.map((x) => `\`${x}\``).join(", ")}.\n`);
  l.push(`Samples: **${ev.n}** across **${ev.groupCount}** groups (actors), **${ev.folds}**-fold actor-grouped CV.\n`);
  l.push("## Headline (calibration-first; NOT a clinical accuracy)\n");
  l.push(`- Accuracy: **${pct(ev.accuracy)}** (95% CI ${pct(ev.significance.accuracyCI95[0])}–${pct(ev.significance.accuracyCI95[1])})`);
  l.push(`- Macro-F1: **${ev.macroF1.toFixed(3)}**`);
  l.push(`- Chance — majority class \`${ev.chance.majorityLabel}\`: ${pct(ev.chance.majorityClassAccuracy)}; stratified-random: ${pct(ev.chance.stratifiedRandomAccuracy)}`);
  l.push(`- Calibration (${ev.calibration.method}): ECE **${ev.calibration.ece.toFixed(3)}**`);
  l.push(
    `- Significance (${ev.significance.test}, ${ev.significance.permutations} perms): null acc ` +
      `${pct(ev.significance.nullMeanAccuracy)}±${(ev.significance.nullStdAccuracy * 100).toFixed(1)}pp, ` +
      `**p=${ev.significance.pValue.toFixed(3)}**, lift over chance ${(ev.significance.observedMinusChance * 100).toFixed(1)}pp`,
  );
  l.push(`\n## Evidence tier: **${ev.evidence.tier.toUpperCase()}**\n`);
  l.push(`${ev.evidence.rationale}\n`);
  l.push("Caveats:");
  for (const c of ev.evidence.caveats) l.push(`- ${c}`);
  l.push("\n## Per-class\n");
  l.push("| label | support | precision | recall | f1 |");
  l.push("|---|---|---|---|---|");
  for (const c of ev.perClass) {
    l.push(`| \`${c.label}\` | ${c.support} | ${c.precision.toFixed(2)} | ${c.recall.toFixed(2)} | ${c.f1.toFixed(2)} |`);
  }
  l.push("\n## Confusion matrix (rows = true, cols = predicted)\n");
  l.push(`| true \\\\ pred | ${ev.confusion.labels.map((x) => `\`${x}\``).join(" | ")} |`);
  l.push(`|---|${ev.confusion.labels.map(() => "---").join("|")}|`);
  ev.confusion.matrix.forEach((row, i) => {
    l.push(`| \`${ev.confusion.labels[i]}\` | ${row.join(" | ")} |`);
  });
  if (ev.notes.length) {
    l.push("\n## Notes\n");
    for (const n of ev.notes) l.push(`- ${n}`);
  }
  return l.join("\n");
}

export function buildModelCardMarkdown(
  model: LogRegParams,
  ev: EvalResult | null,
  trainDatasetId: string,
): string {
  const l: string[] = [];
  l.push(`# Model Card — signal-lab affect-prior LogReg ${model.version}\n`);
  l.push("## Overview");
  l.push(`- **Name / version:** ${model.version}`);
  l.push("- **Status:** trained (baseline; calibration measured, caps NOT raised)");
  l.push("- **Contract implemented:** `AffectExpert` (`@hum-ai/affect-model-contracts`) via `LearnedAffectPriorExpert`");
  l.push("\n## Intended use");
  l.push("- Cold-start AFFECT PRIOR over the fusion label space, consumed by `FusionEngine` and down-weighted by the far-domain penalty.");
  l.push("- **Out of scope / must not be used for:** diagnosis, clinical decisions, hum truth, personalization, relapse tracking (ADR-0005).");
  l.push("\n## Inputs & outputs");
  l.push(`- Input: \`AcousticFeatures\` (${model.featureNames.length}-column vector with null-mask channels).`);
  l.push(`- Output: probability distribution over fusion labels: ${model.labels.map((x) => `\`${x}\``).join(", ")}.`);
  l.push("\n## Training data & priors");
  l.push(`- Dataset: \`${trainDatasetId}\` (acted_speech_emotion), registry domain gap **far**, penalty **0.45**.`);
  l.push(`- Train samples: ${model.trainCount}. Class-weighted: ${model.classWeighted}. L2=${model.l2}, iters=${model.iterations}, lr=${model.learningRate}.`);
  l.push("- Labels harmonized RAVDESS emotion → FUSION_LABELS (disgust/surprised excluded; see label-mapping artifact).");
  l.push("\n## Evaluation");
  if (ev) {
    l.push(`- Accuracy ${pct(ev.accuracy)} (chance ${pct(ev.chance.majorityClassAccuracy)}), macro-F1 ${ev.macroF1.toFixed(3)}, ECE ${ev.calibration.ece.toFixed(3)}, permutation p=${ev.significance.pValue.toFixed(3)}.`);
    l.push(`- Evidence tier: **${ev.evidence.tier}**. Actor-grouped ${ev.folds}-fold CV (no speaker leakage).`);
    l.push("- These are PRIOR-domain metrics on acted speech, NOT Hum metrics and NOT a clinical accuracy.");
  } else {
    l.push("- not yet evaluated");
  }
  l.push("\n## Limitations & risks");
  l.push("- Far domain gap to a hum; acted (performed) affect; no `fatigued` training support (RAVDESS lacks it).");
  l.push("- Abstains under poor capture / domain mismatch / low margin via the existing confidence model.");
  l.push("\n## Safety & privacy");
  l.push("- Risk-marker heads stay behind the two-head/consent boundary; user copy is qualitative only (ADR-0006/0008).");
  l.push("- Raw audio is ephemeral; only derived features are ever stored; weights live git-ignored, never tracked.");
  return l.join("\n");
}

export function buildReadinessMarkdown(args: {
  availability: AvailabilityReport;
  extractions: readonly ExtractionSummary[];
  evaluation: EvalResult | null;
  modelTrained: boolean;
  artifactsDir: string;
}): string {
  const { availability, extractions, evaluation, modelTrained, artifactsDir: dir } = args;
  const l: string[] = [];
  l.push("# Signal-Lab — Model Readiness Report\n");
  l.push(`Artifacts dir (git-ignored): \`${dir}\`\n`);
  l.push("## Data readiness\n");
  l.push(`- Datasets cataloged: ${availability.summary.total}; usable today: ${availability.summary.usable} (${availability.summary.usableIds.join(", ") || "none"}).`);
  for (const d of availability.datasets) {
    l.push(`  - \`${d.datasetId}\`: ${d.status}${d.usableForFeatureExtraction ? "" : " (not usable for extraction)"}`);
  }
  l.push("\n## Feature extraction\n");
  for (const e of extractions) {
    l.push(
      `- \`${e.datasetId}\`: ${e.featureRows} rows (${e.labeledRows} labeled), decoded ${e.decoded}, ` +
        `decode-fail ${e.decodeFailures}, parse-fail ${e.parseFailures}, excluded-by-mapping ${e.excludedByMapping}${e.capped ? ", CAPPED" : ""}.`,
    );
    for (const n of e.notes) l.push(`  - note: ${n}`);
  }
  l.push("\n## Model\n");
  if (modelTrained && evaluation) {
    l.push(`- Trained: affect-prior LogReg. Evidence tier **${evaluation.evidence.tier}** (acc ${pct(evaluation.accuracy)} vs chance ${pct(evaluation.chance.majorityClassAccuracy)}, p=${evaluation.significance.pValue.toFixed(3)}).`);
  } else {
    l.push("- No model trained (insufficient labeled audio). Feature extraction + readiness produced instead (no fabricated model).");
  }
  l.push("\n## What is proven vs not\n");
  l.push("- PROVEN: a dependency-free pipeline that reads prepared public audio zip-direct, extracts the real `AcousticFeatures`, harmonizes RAVDESS labels to FUSION_LABELS, trains a baseline, and reports calibration + significance honestly.");
  l.push("- NOT PROVEN: any statement about a real user's hum. All evidence is far-domain acted-speech PRIOR only (ADR-0005). No native hum corpus exists.");
  l.push("- BLOCKED/MISSING: CREMA-D audio (LFS not pulled), DEAM/MTG-Jamendo audio (separate large downloads), clinical/access-pending corpora (no local bytes).");
  l.push("- INTENTIONALLY NOT DONE: heavy SSL training (torch/transformers) — the repo defers it to the Python `research/` scaffold and forbids new heavy deps without approval.");
  return l.join("\n");
}

/** Compact, human-readable one-screen summary of an inference report. */
export function buildInferenceMarkdown(r: InferenceReport): string {
  const l: string[] = [];
  l.push("# Signal-Lab — Inference Evidence Report\n");
  l.push(`- Model: ${r.modelUsed.kind} (\`${r.modelUsed.id}\`, ${r.modelUsed.version})${r.fallbackUsed ? " — FALLBACK" : ""}`);
  l.push(`- Artifact: ${r.artifactUsed ?? "(in-memory / none)"}`);
  l.push(`- Capture: ${r.features.durationSec.toFixed(1)}s, quality ${r.quality.captureQuality} (${r.quality.decision}); domain heard '${r.domain.predicted}' (match ${r.domain.domainMatch.toFixed(2)}).`);
  l.push(`- Inferred: ${r.inferredState.abstained ? "ABSTAINED" : `dominant '${r.inferredState.dominantBroadState}', V=${r.inferredState.valence.toFixed(2)} A=${r.inferredState.arousal.toFixed(2)}`}`);
  if (r.inferredState.stateCandidates.length) {
    l.push(`- Candidates: ${r.inferredState.stateCandidates.map((c) => `${c.fusionLabel} ${(c.probability * 100).toFixed(0)}%`).join(", ")}`);
  }
  l.push(`- Confidence: ${r.confidence.qualitative.signalClarity} · ${r.confidence.qualitative.basedOn} (internal cap ${r.confidence.internal.appliedCap.toFixed(2)} — ${r.confidence.internal.capReason}); uncertainty ${r.confidence.uncertainty.toFixed(2)}; stage ${r.confidence.stage}.`);
  l.push(`- Intervention: ${r.intervention.surfaced ? `${r.intervention.type} — ${r.intervention.rationale}` : "(none surfaced)"}`);
  if (r.promotion.evaluated) {
    const ba = r.promotion.affectBalancedAccuracy;
    l.push(
      `- Promotion gate (${r.promotion.gateMetric} ≥ ${(r.promotion.gateThreshold * 100).toFixed(0)}%): affect target ` +
        `${r.promotion.affectPassedGate ? "PASSED" : "did NOT pass"}${ba !== null ? ` (${(ba * 100).toFixed(1)}%)` : ""} → ${r.promotion.affectPassedGate ? "gate-validated" : "population prior only"}` +
        `${r.promotion.promotedAuxTarget ? `; coarse '${r.promotion.promotedAuxTarget}' axis passed as a far-domain prior (not driving this read)` : ""}.`,
    );
  }
  if (r.neuralAuxiliaryPrior) {
    const a = r.neuralAuxiliaryPrior;
    l.push(
      `- Neural aux prior (\`${a.target}\`, ${a.family}): '${a.topLabel}' ${(a.probability * 100).toFixed(0)}% ` +
        `(balAcc ${(a.balancedAccuracy * 100).toFixed(1)}%) — auxiliary only, not steering.`,
    );
  }
  if (r.support.topFeatureContributions.length) {
    l.push(`- Top supporting features: ${r.support.topFeatureContributions.slice(0, 5).map((c) => `${c.feature}(${c.contribution >= 0 ? "+" : ""}${c.contribution.toFixed(2)})`).join(", ")}`);
  }
  l.push("\nWarnings:");
  for (const w of r.warnings) l.push(`- ${w}`);
  return l.join("\n");
}
